application: jcgregorio-test
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  expiration: 2m 20s
  
- url: /images
  static_dir: images
  
- url: .*
  script: main.py
  secure: always

